up-csi/dcs-website-2.0

directus-backend/docker-compose.yaml
This PR replaces relative paths defined in the `volumes` field in `docker-compose.yaml` with named volumes.
This also enforces the use of docker container-provided volumes for file storage rather than putting the files in the project's root repository.
=> chore(backend): use named docker volumes for directus volumes

website-frontend/src/lib/models/schema.ts, website-frontend/src/lib/models/student_council.ts, website-frontend/src/routes/+page.ts
This PR adds the `StudentCouncil` model for valibot validation in the frontend, with respect to the resolved Student Council collection in the CMS.
=> feat(frontend): add `StudentCouncil` model for valibot

website-frontend/tests/collections.spec.ts
This PR adds testing to the defined `student_council` model along with improvements to test code semantics.
=> test(models): add `student_council` testing and improve test semantics

.github/workflows/codequality.yml, .github/workflows/commitlint.yml, .github/workflows/playwright.yml, website-frontend/package.json
This PR adds code quality checks in the frontend, enforcing the use of Prettier and ESLint checks. This PR also incorporates `svelte-check` for Svelte components diagnostics.
This PR also creates two separate `pnpm` scripts, mainly `lint:prettier-only` and `lint:eslint-only`, for finer granularity in GitHub workflow reports.
=> ci: add code quality check

.github/workflows/codequality.yml, .github/workflows/playwright.yml
This PR elevates repository access privileges for test workflows, namely, `playwright.yml` and `codequality.yml`, to access repository variables such as `PUBLIC_APIURL`.
This PR also sanitizes some configurations like removing the `fetch-depth` outside `commitlint` and changing the scope of `PUBLIC_APIURL` to the desired step level. In addition, this PR fixed a bug regarding the playwright artifact step not showing up due to the misconfiguration of `path`.
=> ci: elevate test workflow access for `vars`

website-frontend/src/lib/models/alumni.ts, website-frontend/src/lib/models/schema.ts, website-frontend/src/routes/+page.ts, website-frontend/tests/collections.spec.ts
This PR adds the `Alumni` model for valibot validation in the frontend, with respect to the resolved Alumni collection in the CMS.
=> feat(frontend): add `Alumni` model for valibot

website-frontend/playwright.config.ts, website-frontend/tests/layout.spec.ts
This PR adds tests for the navigation bar, resolving testing for items:
- 2-4: Navigation Bar Links to Home
- 2-5: Navigation Bar Links to Events
- 2-6: Navigation Bar Links to Alumni
- 2-7: Navigation Bar Links to People
- 2-12: Navigation Bar Links to About, with dropdowns to subpages
It should be noted that the linked pages do not yet exist, but the tests will trivially pass as long as the links lead to routes whose URLs include the name of the page. Once we have dynamic page titles implemented, I recommend using those as a basis for testing.
=> feat(test): add NavBar tests

website-frontend/.prettierrc, website-frontend/package.json, website-frontend/pnpm-lock.yaml, website-frontend/src/lib/components/nav/NavBar.svelte, website-frontend/src/lib/components/nav/NavItem.svelte, website-frontend/src/routes/+page.svelte, website-frontend/src/routes/academics/[slug]/+page.svelte
This PR adds the `prettier-plugin-tailwindcss` plugin for prettier. This ensures more consistency upon reading and writing tailwind CSS code for website components.
=> build(deps): add prettier-plugin-tailwindcss

website-frontend/src/lib/components/events/FeaturedEventCard.svelte, website-frontend/src/routes/+page.svelte, website-frontend/src/routes/events/+page.svelte
This PR...
- links the home page to the events page via the "View all" link above the featured events
- features events in both the home and the events pages based on recency
- shows all events in the events page
- adds responsive CSS to the layouts of the events page and the featured events in the home page
=> feat(Events): show events

website-frontend/src/lib/models/linkages.ts, website-frontend/src/lib/models/schema.ts, website-frontend/src/routes/+layout.server.ts, website-frontend/src/routes/+layout.ts
This pull request introduces a new `Linkages` model to the website front-end. The changes include defining the `Linkages` model, integrating it into the schema, and updating the layout to load `linkages` data.
This refers to [#72 in Taiga](https://tree.taiga.io/project/veeisforvanana-dcs-website-revamp/us/72?kanban-include_attachments=1&kanban-include_tasks=1&kanban-status=9725320). The path to the partnership page was not created because I believe it might be intended for the navigation bar ticket instead.
=> feat(frontend): add `linkages` model

website-frontend/src/lib/components/nav/Header.svelte, website-frontend/src/lib/server/assets.ts, website-frontend/src/lib/server/download.ts, website-frontend/src/lib/server/schema.ts, website-frontend/src/routes/+layout.server.ts, website-frontend/src/routes/+layout.svelte, website-frontend/src/routes/+layout.ts, website-frontend/src/routes/+page.server.ts, website-frontend/src/routes/+page.svelte, website-frontend/src/routes/+page.ts, website-frontend/src/routes/academics/+page.server.ts, website-frontend/src/routes/academics/+page.svelte, website-frontend/src/routes/academics/[slug]/+page.server.ts, website-frontend/src/routes/academics/[slug]/+page.svelte, website-frontend/src/routes/events/+page.server.ts, website-frontend/src/routes/events/+page.svelte, website-frontend/src/routes/events/+page.ts, website-frontend/src/routes/people/+page.server.ts, website-frontend/src/routes/people/+page.svelte, website-frontend/src/routes/people/[slug]/+page.server.ts, website-frontend/src/routes/people/[slug]/+page.svelte, website-frontend/src/routes/people/[slug]/[username]/+page.server.ts, website-frontend/src/routes/people/[slug]/[username]/+page.svelte, website-frontend/src/routes/research/overview/+page.server.ts
This PR limits data returns such that only the specified schema and assets will be requested from Directus CMS and eventually be used in the needed pages.
Requires:
=> refactor: limit data returns for routes

website-frontend/src/lib/server/schema.ts, website-frontend/src/routes/+page.svelte, website-frontend/src/routes/events/+page.svelte
This PR uses sort by recency as the default query parameter for fetching events in the home and events pages. This PR also utilizes Directus CMS query parameters to sort returned events automatically rather than sorting the events themselves in the frontend.
Requires:
=> feat: use sort by recency as default for events

website-frontend/src/lib/server/schema.ts
This PR removes the extraneous `Schema` type annotation in `schema.ts`, resulting in `svelte-check` code quality workflow error.
=> fix: remove extraneous `Schema` type annotation

website-frontend/src/lib/server/schema.ts
This PR fixes the `obtainSchema` return in `schema.ts` by concatenating entries from `Object.entries(schema).filter(...)` and then formulating the result as an object through `Object.fromEntries`.
=> fix: concat schema entries

website-frontend/package.json, website-frontend/pnpm-lock.yaml
This PR resolves some longstanding issues with missing environment variable exports during testing by providing an `env:dev` subcommand for `pnpm` to automatically export the environment file.
Please be aware that upon merging this feature, all `.env` files must be renamed `.env.development` to work with the specifications of the command.
=> feat!: use dotenv to handle environment variables

website-frontend/src/lib/components/flexible_content/FlexibleContent.svelte, website-frontend/src/lib/components/flexible_content/index.ts, website-frontend/src/lib/components/nav/NavBar.svelte, website-frontend/src/lib/models/about.ts, website-frontend/src/lib/models/about_pages.ts, website-frontend/src/lib/models/schema.ts, website-frontend/src/routes/about/+page.server.ts, website-frontend/src/routes/about/+page.svelte, website-frontend/src/routes/about/[slug]/+page.server.ts, website-frontend/src/routes/about/[slug]/+page.svelte
This PR includes significant updates to the `about` section and improve content rendering. This takes on tickets #66-#71 in Taiga.
* Added a server-side load function to fetch and parse the 'about' singleton from Directus.
* Created a new page component to display the about content using the `FlexibleContent` component.
* Added a server-side load function to fetch about pages by slug from Directus.
* Created a new page component to display about pages by slug using the `FlexibleContent` component.
* Added a new Svelte component to render enhanced WYSIWYG content.
* Introduced `enhanceWysiwygContent` function to apply styles to various HTML elements.
* Added a new `About` model to handle the about content with HTML cleaning.
* Added new `AboutPage` and `AboutPages` models to handle …
=> feat: add `about_pages` model

website-frontend/src/lib/directus.ts, website-frontend/src/lib/models/schema.ts, website-frontend/src/lib/models/student_council.ts, website-frontend/src/lib/server/schema.ts, website-frontend/tests/collections.spec.ts
This PR removes the stale student_council singleton collection in the valibot parsing of schema and playwright testing.
=> fix: remove student_council singleton collection

website-frontend/src/lib/components/events/DetailsBanner.svelte, website-frontend/src/lib/components/events/FeaturedEventCard.svelte, website-frontend/src/lib/directus.ts, website-frontend/src/lib/models/event.ts, website-frontend/src/lib/models/schema.ts, website-frontend/src/lib/models/student_council.ts, website-frontend/src/lib/server/schema.ts, website-frontend/src/routes/+layout.server.ts, website-frontend/src/routes/+page.server.ts, website-frontend/src/routes/about/+page.server.ts, website-frontend/src/routes/about/[slug]/+page.server.ts, website-frontend/src/routes/events/+page.server.ts, website-frontend/src/routes/events/[slug]/+page.server.ts, website-frontend/src/routes/events/[slug]/+page.svelte, website-frontend/src/routes/people/+page.server.ts, website-frontend/src/routes/people/[slug]/+page.server.ts, website-frontend/src/routes/people/[slug]/[username]/+page.server.ts, website-frontend/src/routes/research/+page.server.ts, website-frontend/src/routes/students/+page.server.ts, website-frontend/src/routes/students/[slug]/+page.server.ts, website-frontend/src/routes/students/organizations/+page.server.ts, website-frontend/tests/collections.spec.ts
This PR sets the website's authentication method to use a static token for extended use. As such, the developers and maintainers should set the correct value for the private environment variable STATIC_ACCESS_TOKEN.
This PR also tries to resolve the 502 Bad Gateway error thrown by PUBLIC_APIURL/auth/login while using the website for an extended time.
=> feat: use static token for website auth

.github/workflows/codequality.yml
This PR adds access to `STATIC_ACCESS_TOKEN` to the code quality workflow.
=> ci: add static token to code quality workflow

website-frontend/src/lib/components/events/FeaturedEventCard.svelte, website-frontend/src/lib/models/event.ts, website-frontend/src/routes/+page.server.ts, website-frontend/src/routes/events/+page.server.ts, website-frontend/src/routes/events/[slug]/+page.server.ts, website-frontend/src/routes/research/+page.server.ts, website-frontend/src/routes/students/+page.server.ts
This PR uses the event collection's many-to-many (M2M) `event_tags` field to access related events by shared tags.
=> feat: use M2M event tags for related events

website-frontend/src/lib/components/nav/NavList.svelte, website-frontend/src/lib/models/publications.ts, website-frontend/src/lib/models/schema.ts, website-frontend/src/routes/publications/+page.server.ts, website-frontend/src/routes/publications/+page.svelte
This pull request introduces a new feature to the website frontend, adding a "Publications" section.
* Added a new navigation item for "Publications".
* Created a new data model for publications, including types for `Author`, `AccessLink`, and `Publication`.
* Integrated the new `Publications` model into the existing schema.
* Implemented server-side code to fetch publications from the Directus CMS, sorted by publish date.
This does not yet implement sorting. Errors with schema validation disallow the use of nested fields. Also, since the `authors` field is in json format and not a string, it could not be sorted natively using directus commands. Will commit changes later on to transform the data instead.
=> feat: add Publications

website-frontend/src/lib/components/filter/FilterBar.svelte, website-frontend/src/lib/components/filter/FilterButton.svelte, website-frontend/src/lib/models-helpers.ts, website-frontend/src/lib/models/event.ts, website-frontend/src/lib/models/events_areas.ts, website-frontend/src/lib/models/events_tags.ts, website-frontend/src/lib/models/events_tags_categories.ts, website-frontend/src/lib/models/junctions/events_related.ts, website-frontend/src/lib/models/schema.ts, website-frontend/src/routes/+page.server.ts, website-frontend/src/routes/events/+page.server.ts, website-frontend/src/routes/events/+page.svelte, website-frontend/src/routes/events/+page.ts, website-frontend/src/routes/events/[slug]/+page.server.ts
This PR adds filter by discipline category logic through the use of the discipline tag inside the `events_tags_categories` collection and generalizes filter options through dedicated fetches.
=> feat: generalize events filters

website-frontend/src/routes/events/+page.server.ts
This PR orders event filter fields based on their specifications. Specifically, location filters are sorted by their `order` field, while discipline filters are sorted alphabetically.
=> feat: add sort to event filter fields

website-frontend/src/lib/components/flexible_content/FlexibleContent.svelte, website-frontend/src/lib/components/flexible_content/index.ts, website-frontend/src/routes/about/+page.svelte, website-frontend/tailwind.config.ts
This PR resolves the issue of the lack of styling in the flexible content container components (#62) by adding style to the component through the installation of the Tailwind typography plugin. In addition, with this plugin it overrides and modifies some of the established styles in the element class map in the main flexible content container.
- **feat: use typography plugin**
- **feat: change per-element styles**
=> fix: enhance flexible content component style

website-frontend/src/routes/academics/+page.svelte, website-frontend/src/routes/academics/[category]/+page.svelte
This PR fixes nav links for fetched academics programs in academics overview page and academics programs subpages.
Requires:
- #89
=> fix: set correct nav links for fetched academics programs

website-frontend/src/lib/utils.ts
This pull request includes a small change to the `deslugify` function in the `website-frontend/src/lib/utils.ts` file. The change ensures that words with apostrophes are correctly handled and that only the first character of each word is capitalized, while the rest of the word is converted to lowercase.
Can be observed when Citizen's Charter is passed as `page.title` for the `<Banner>` and returns Citizen'S Charter after deslugification.
=> fix: proper deslugify when word has apostrophe

website-frontend/src/lib/components/banners/PeopleBanner.svelte, website-frontend/src/lib/components/cards/PeopleCard.svelte, website-frontend/src/lib/components/panel/CardPanel.svelte, website-frontend/src/routes/people/+page.svelte, website-frontend/src/routes/people/[slug]/+page.svelte, website-frontend/src/routes/people/[slug]/[username]/+page.svelte
This PR introduces several improvements to the People pages:  
- **Breadcrumbs:** Added to the People subpages for better navigation. *(Note: it is not yet responsive.)*  
- **UI Enhancements:**  
- Adjusted the PeopleCard layout.  
- Improved the mobile People details page.  
- **Aggregation:** Added headings & aggregation in the main People page for better organization.  
- **Conditional Website Button:** The website button is now hidden when unavailable in the People details page.  
Additionally:
- **CardPanel Update:** Ensures a minimum of **two columns**, even on smaller screens.
=> feat: adjust people pages

package.json, website-frontend/package.json, website-frontend/pnpm-lock.yaml, website-frontend/src/routes/+error.svelte, website-frontend/svelte.config.js
This PR changes the build adapter from `adapter-auto` to `adapter-node` by installing and importing the relevant package in `svelte.config.ts`. Further, it also designates `pnpm` as the package manager in `package.json`.
=> feat: use adapter-node

website-frontend/src/routes/+error.svelte
This PR fixes a naming issue in accessing the `page` store on the error page.
- feat: change adapter to adapter-node
- feat: designate pnpm as package manager
- feat: remove package manager key in package.json
- fix: use $app/stores instead of $app/state
- fix: fix page store access in error page
=> fix: solve error page issues

website-frontend/src/routes/academics/+page.server.ts, website-frontend/src/routes/academics/+page.svelte, website-frontend/src/routes/academics/[category]/+page.server.ts, website-frontend/src/routes/academics/[category]/+page.svelte
This pull request to the `website-frontend` project includes updating the server-side load functions to fetch new data, modifying the Svelte components to use the fetched data, and replacing static links with dynamically generated ones.
Enhancements to data fetching:
* Added a request to fetch `academics_categories` and included it in the returned data.
* Replaced the request for `academics_courses` with a request for `academics_pages` and included it in the returned data.
* Added `HorizontalCard` component, updated the reactive statement to include `academics_categories`, and replaced static links with dynamically generated cards for each academic category.
* Updated the reactive statement to include `academics_pages` and replaced static links with dynamically generated links for each …
=> feat: load academics subcollections for subpages

.dockerignore, .github/workflows/deploy.yml, Dockerfile
This PR sets up a deployment flow for the frontend by adding a `Dockerfile` and `.dockerignore` to the repository root. I will admit that due to the _weird_ structure of our project, it does have to do a few awkward maneuvers to get to the needed files, but this workflow generally works. 
Aside from the deployment system itself, this PR also adds a GitHub Workflow to build and push the Docker image to the GHCR registry, allowing for remote access of the latest build with each push to main.
I will try to modify the existing `docker-compose.yaml` in the backend to include pulling the frontend image from the registry to massively simplify our deployment flow, but this can also be addressed in another PR.
=> feat: add deployment system using docker

website-frontend/src/app.postcss, website-frontend/src/lib/components/panel/CardPanel.svelte, website-frontend/src/routes/people/+page.svelte, website-frontend/src/routes/people/[slug]/+page.svelte
This PR adds division by rank in the people pages. Let me know if the ranks need to be arranged in a specific order!
Additionally:
- Made minor edits to the `CardPanel` component:
- Removed the bottom padding.
- Note: Further styling changes are still needed for `CardPanel`. The cards should be left-aligned rather than centered when there aren’t enough cards for a full row. This will be addressed in a separate PR.
=> feat: add division by rank in people pages

Dockerfile
This PR fixes the current issue with the Docker deployment action by explicitly setting the Dockerfile syntax version.
=> fix: explicitly detail docker syntax

.github/workflows/deploy.yml
This PR corrects the misplacement of the `secrets` argument for the Build action, preventing the connection secrets from being registered with the Docker container properly.
=> fix: correct misplacement of build secrets in deployment workflow

website-frontend/src/lib/components/list_items/NavItem.svelte
This PR patches a bug where the mobile navbar fails to close on `NavItem` click.
=> fix: close mobile navbar on `NavItem` click

website-frontend/src/app.html, website-frontend/src/lib/components/breadcrumbs/PageBreadcrumb.svelte, website-frontend/src/routes/+page.svelte
This PR addresses minor issues in the maintenance list:
- "From Safari and Chrome mobile, the footer is not displaying properly.": 
- The **_entire frontend_** is not displaying properly in both Safari and Chrome mobile, except for the landing heroes and the banners.
- Had a feeling that it's because of the `h-screen` class in the `<body>` tag in `app.html`, so I removed it. Adding `overflow-scroll` instead of removing the `h-screen` class *might* probably work as well.
- "Fix routing issue when selecting view all from the home page": fixed it na hooray
=> fix: patch minor bugs

website-frontend/src/routes/people/+page.svelte, website-frontend/src/routes/people/[slug]/+page.svelte
This PR adds the filters to the people pages.
- Implemented the filters by position for people routes
- Implemented the filters by laboratory for people routes
- Added a note that shows when there are no people found matching the chosen filters
=> feat: add lab and position filters to people routes

website-frontend/src/lib/components/buttons/ShowMoreCourseDetails.svelte, website-frontend/src/lib/components/table/CoursesTable.svelte, website-frontend/src/lib/models/academics_courses.ts
This PR adds a display to the course syllabus link in academics courses if the course syllabus link exists in the CMS.
=> feat: add course syllabus link display in academics courses

website-frontend/src/lib/components/carousels/LabHero.svelte
This PR removes the use of `deslugify` function in Hero banner component for displaying the data title.
=> fix: remove deslugify title in hero banner

directus-backend/docker-compose.yaml
This PR updates the `docker-compose.yaml` file here to include the steps for setting up the frontend image, aligning it with the present state of the currently-running preview.
=> feat: add frontend image to docker compose

website-frontend/src/lib/components/banners/Banner.svelte, website-frontend/src/lib/components/banners/EventBanner.svelte, website-frontend/src/lib/components/banners/PeopleBanner.svelte, website-frontend/src/lib/components/cards/AlumCard.svelte, website-frontend/src/lib/components/cards/FeaturedEventCard.svelte, website-frontend/src/lib/components/cards/HorizontalCard.svelte, website-frontend/src/lib/components/cards/NewsCard.svelte, website-frontend/src/lib/components/cards/PartnerCard.svelte, website-frontend/src/lib/components/cards/PeopleCard.svelte, website-frontend/src/lib/components/cards/PublicationCard.svelte, website-frontend/src/lib/components/carousels/LabHero.svelte, website-frontend/src/lib/components/carousels/LandingHero.svelte, website-frontend/src/lib/components/list_items/LaboratoryItem.svelte, website-frontend/src/lib/components/list_items/OrganizationItem.svelte, website-frontend/src/lib/components/nav/Header.svelte, website-frontend/src/lib/components/nav/NavList.svelte, website-frontend/src/lib/components/search/SearchResult.svelte, website-frontend/src/lib/components/table/Calendar.svelte, website-frontend/src/routes/+layout.svelte, website-frontend/src/routes/news/[slug]/+page.svelte
This PR addresses the following:
* Use dynamic resolution for fetching images in the Directus CMS using Svelte's dimensional bindings (`clientHeight` and `clientWidth`) _except_ for small logos.
* Fix infinite loading screen during back navigation by _always_ setting `$reloading` to `false` in the global `+layout.svelte` script.
* Use `left-full` to align nested dropdown elements in the navigation bar for `academics/[category]/[slug]` and `research/labs/[slug]`.
=> fix: apply dynamic image scaling and UI bug fixes
