up-csi/dcs-website-2.0

.github/workflows/playwright.yml
website-frontend/.github/workflows/playwright.yml
website-frontend/.gitignore
website-frontend/package.json
website-frontend/playwright.config.ts
website-frontend/pnpm-lock.yaml
website-frontend/src/lib/models-helpers.ts
website-frontend/tests/acads.spec.ts
website-frontend/tests/editing.spec.ts
website-frontend/tests/events.spec.ts
website-frontend/tests/example.spec.ts
website-frontend/tests/faculty.spec.ts
website-frontend/tests/hierarchy.spec.ts
website-frontend/tests/home.spec.ts
website-frontend/tests/layout.spec.ts
website-frontend/tests/members.spec.ts
website-frontend/tests/metadata.spec.ts
website-frontend/tests/orgs.spec.ts
website-frontend/tests/pubs.spec.ts
website-frontend/tests/research.spec.ts

This PR sets up Playwright for frontend E2E (end-to-end) testing to accommodate use cases in the DCS Website 2.0 RTM (Requirements Traceability Matrix).
This PR also includes blank test files that correspond to each defined use case. The file names can be changed anytime.

test(frontend): setup playwright

---

.github/workflows/codequality.yml
.github/workflows/playwright.yml

This PR adds performance improvements in running GitHub workflows by caching NodeJS and pnpm installations in the GitHub actions runner machine.

perf(ci): cache node and pnpm in workflows

---

website-frontend/src/app.html
website-frontend/src/routes/+layout.svelte

This PR adds dynamic title functionality to the website through the changes in the CMS.

feat(metadata): add dynamic title through global fetch

---

website-frontend/src/app.postcss
website-frontend/src/lib/components/nav/NavBar.svelte
website-frontend/tailwind.config.ts

This PR tries to match navbar shape and typography to the specifications in the Figma prototype. Note that the color scheme does not match the prototype color scheme yet.

feat(navbar): match navbar shape to prototype

---

website-frontend/src/routes/people/+page.svelte

This PR fixes some issues raised in CI/CD by running the linter with write permissions.

chore: run linter

---

website-frontend/src/lib/components/load_more/LoadMore.svelte
website-frontend/src/routes/events/+page.svelte
website-frontend/src/routes/people/+page.svelte
website-frontend/src/routes/people/[slug]/+page.svelte

This PR generalizes the load more button by adding a `LoadMore` button component.

feat: add `LoadMore` component

---

website-frontend/src/lib/components/events/DetailsBanner.svelte
website-frontend/src/lib/components/events/FeaturedEventCard.svelte
website-frontend/src/lib/directus.ts
website-frontend/src/lib/models/event.ts
website-frontend/src/lib/models/schema.ts
website-frontend/src/lib/models/student_council.ts
website-frontend/src/lib/server/schema.ts
website-frontend/src/routes/events/[slug]/+page.svelte
website-frontend/tests/collections.spec.ts

This PR changes the event location schema for valibot parse validation, reflective of the changes made in the Directus CMS.

fix!: change event location schema

---

website-frontend/src/lib/components/filter/FilterBar.svelte

This PR changes the style of the filter bar when viewed on phones.

style(Filter): restyle mobile filter bar

---

website-frontend/src/lib/components/events/DetailsBanner.svelte
website-frontend/src/lib/components/events/FeaturedEventCard.svelte
website-frontend/src/lib/models-helpers.ts
website-frontend/src/lib/models/event.ts
website-frontend/src/routes/events/[slug]/+page.server.ts
website-frontend/src/routes/events/[slug]/+page.svelte

This PR adds logic for related events part of an event's details page.

feat: add related events logic

---

website-frontend/src/app.postcss
website-frontend/src/lib/components/card/PublicationCard.svelte
website-frontend/src/lib/components/panel/CardPanel.svelte
website-frontend/src/lib/components/people/PeopleCard.svelte
website-frontend/src/routes/people/+page.svelte
website-frontend/src/routes/people/[slug]/+page.svelte
website-frontend/src/routes/research/outputs/+page.server.ts
website-frontend/src/routes/research/outputs/+page.svelte

This PR...
- fixes the responsive CSS of the panel showcasing people and publication cards, and
- implements the featured outputs page.

feat: add featured outputs page

---

website-frontend/src/lib/components/card/PublicationCard.svelte

This PR fixes the `svelte-check` error in the `PublicationCard` component.

fix(PublicationCard): fix `svelte-check` error

---

website-frontend/src/lib/components/footer/Footer.svelte
website-frontend/src/lib/components/nav/Header.svelte
website-frontend/src/lib/models/global.ts
website-frontend/src/routes/+layout.svelte
website-frontend/src/routes/+layout.ts

This PR adds the footer component.

feat: add footer

---

website-frontend/src/lib/components/flexible_content/FlexibleContent.svelte
website-frontend/src/lib/models/directus_users.ts
website-frontend/src/lib/models/news.ts
website-frontend/src/lib/models/schema.ts
website-frontend/src/routes/+page.server.ts
website-frontend/src/routes/+page.svelte
website-frontend/src/routes/+page.ts
website-frontend/src/routes/news/[slug]/+page.server.ts
website-frontend/src/routes/news/[slug]/+page.svelte
website-frontend/tailwind.config.ts

This PR adds barebones news displays on the home page and its items' details pages.

feat: add barebones news displays

---

website-frontend/src/lib/@shadcn-svelte/ui/card/card-content.svelte
website-frontend/src/lib/@shadcn-svelte/ui/card/card-description.svelte
website-frontend/src/lib/@shadcn-svelte/ui/card/card-footer.svelte
website-frontend/src/lib/@shadcn-svelte/ui/card/card-header.svelte
website-frontend/src/lib/@shadcn-svelte/ui/card/card-title.svelte
website-frontend/src/lib/@shadcn-svelte/ui/card/card.svelte
website-frontend/src/lib/@shadcn-svelte/ui/card/index.ts
website-frontend/src/lib/@shadcn-svelte/ui/dialog/dialog-content.svelte
website-frontend/src/lib/@shadcn-svelte/ui/dialog/dialog-description.svelte
website-frontend/src/lib/@shadcn-svelte/ui/dialog/dialog-footer.svelte
website-frontend/src/lib/@shadcn-svelte/ui/dialog/dialog-header.svelte
website-frontend/src/lib/@shadcn-svelte/ui/dialog/dialog-overlay.svelte
website-frontend/src/lib/@shadcn-svelte/ui/dialog/dialog-portal.svelte
website-frontend/src/lib/@shadcn-svelte/ui/dialog/dialog-title.svelte
website-frontend/src/lib/@shadcn-svelte/ui/dialog/index.ts
website-frontend/src/lib/components/card/PublicationCard.svelte
website-frontend/src/lib/models/publications.ts
website-frontend/src/routes/publications/+page.server.ts
website-frontend/src/routes/publications/+page.svelte
website-frontend/src/routes/publications/+page.ts
website-frontend/src/routes/research/outputs/+page.svelte

This PR populates the Publications page with Publications cards with initial filter controls.

feat: add publications content

---

website-frontend/src/lib/components/cards/NewsCard.svelte
website-frontend/src/lib/components/carousels/LandingHero.svelte
website-frontend/src/lib/components/events/FeaturedEventCard.svelte
website-frontend/src/lib/components/footer/Footer.svelte
website-frontend/src/lib/models/news.ts
website-frontend/src/routes/+page.svelte

This PR adds the home page content based on the prototype specifications.

feat: add home page content

---

website-frontend/src/lib/components/search/SearchInput.svelte
website-frontend/src/routes/news/[slug]/+page.server.ts
website-frontend/src/routes/news/[slug]/+page.svelte
website-frontend/src/routes/search/+page.server.ts
website-frontend/src/routes/search/+page.svelte

This PR adds news details page styling based on the project prototype.
Requires #102 to be merged first.

feat: add news details page styling

---

website-frontend/src/lib/components/footer/Footer.svelte
website-frontend/src/lib/components/nav/Header.svelte
website-frontend/src/lib/models/global.ts
website-frontend/src/routes/+layout.svelte
website-frontend/src/routes/+layout.ts

This PR aligns header and footer specifications to the project prototype.
Requires #102 and #103 to be merged first.

feat: align header and footer specs

---

website-frontend/src/lib/components/nav/Header.svelte
website-frontend/src/routes/+layout.svelte
website-frontend/src/routes/+page.svelte
website-frontend/src/routes/news/[slug]/+page.svelte

This PR improves the current page layout to enhance user experience.

feat: improve page layout

---

website-frontend/src/routes/+error.svelte

This PR adds an error page for the website.

feat: add error page

---

website-frontend/src/lib/components/table/Calendar.svelte
website-frontend/src/routes/events/+page.svelte

This pull request introduces a new `Calendar` component to the `website-frontend` project and integrates it into the events page.
* Added a new `Calendar` component to display events in a calendar view. This includes functions for navigating between months, formatting event dates and times, and rendering events with their details.
* Replaced the `LoadMore` button and the list of events with the new `Calendar` component to enhance the user experience when browsing events.

feat: add Events Calendar

---

website-frontend/src/lib/models/junctions/publications_related.ts
website-frontend/src/lib/models/publications.ts
website-frontend/src/lib/models/publications_tags.ts
website-frontend/src/lib/models/schema.ts
website-frontend/src/routes/publications/+page.server.ts
website-frontend/src/routes/publications/+page.svelte
website-frontend/src/routes/publications/+page.ts

This PR adds publications filtering by tags.
Requires #113 based on the PR's code base.

feat: add publications tags filters

---

website-frontend/src/app.postcss
website-frontend/src/lib/components/carousels/LandingHero.svelte
website-frontend/src/lib/components/footer/Footer.svelte
website-frontend/src/lib/components/nav/Header.svelte
website-frontend/src/lib/components/nav/NavItem.svelte
website-frontend/src/routes/+page.svelte
website-frontend/tailwind.config.ts

This PR introduces various UI refinements and behavior improvements across the navbar, header, and `LandingHero` component:  
- Color adjustments and refinements.  
- **Improved navbar behavior:** It now **appears when scrolling up** and **hides when scrolling down** for a smoother experience.  
- **`primary-dark`** – Intended for text.  
- **`background-dark`** – Used as the footer background color.  
- Updated **`primary` color** to **DCS green** for consistency.  
- Added a **progress bar** to page indicators for better UX feedback.  
- Introduced **animated text effects**.  
- Adjusted **text, colors, and height** for a more polished design.

feat: improve styling for navbar, header, and LandingHero

---

website-frontend/src/lib/components/sort/Sort.svelte
website-frontend/src/routes/publications/+page.server.ts
website-frontend/src/routes/publications/+page.svelte
website-frontend/src/routes/publications/+page.ts

This PR enhances the current publications sort to match sort controls to the project specifications.

feat: enhance publications sort

---

website-frontend/src/routes/students/organizations/[slug]/+page.server.ts
website-frontend/src/routes/students/organizations/[slug]/+page.svelte
website-frontend/src/routes/students/organizations/[slug]/+page.ts

This PR adds event and news carousels to organization subpages.

feat(Organizations): add carousels

---

website-frontend/src/app.postcss
website-frontend/src/lib/components/cards/FeaturedEventCard.svelte
website-frontend/src/lib/components/cards/NewsCard.svelte
website-frontend/src/lib/components/carousels/CardCarousel.svelte
website-frontend/src/lib/components/carousels/LandingHero.svelte
website-frontend/src/lib/components/footer/Footer.svelte
website-frontend/src/lib/components/list_items/NavItem.svelte
website-frontend/src/lib/components/nav/Header.svelte
website-frontend/src/routes/+layout.svelte
website-frontend/src/routes/+page.svelte
website-frontend/src/routes/academics/+page.svelte
website-frontend/src/routes/events/+page.svelte
website-frontend/src/routes/events/[slug]/+page.svelte
website-frontend/src/routes/news/[slug]/+page.svelte
website-frontend/src/routes/research/labs/[slug]/+page.svelte
website-frontend/src/routes/students/organizations/[slug]/+page.svelte
website-frontend/tailwind.config.ts

- Created `CardCarousel` component to standardize carousel behavior.
- Made styling of `FeaturedEventCard` and `NewsCard` more consistent across the app.
- Implemented mobile UI corrections:
- Changed mobile navigation menu background to `background-dark`.
- Fixed padding issues in mobile navigation menu.
- Set department name text size to fixed on mobile.
- Corrected the logo displayed in the mobile navigation menu.
- Added **DCS Red** as `secondary-red` for consistent branding.
- Introduced new utility classes: `.content-padding`, `.heading-padding`, and `.heading-text` (still to be applied across all pages).
- Various minor styling adjustments to improve the layout on the landing page.
- Corrected footer padding for better alignment.

feat: overhaul card carousel component and perform ui fixes

---

website-frontend/src/lib/components/cards/AlumCard.svelte
website-frontend/src/lib/models/alumni.ts
website-frontend/src/lib/models/alumni_overview.ts
website-frontend/src/lib/models/schema.ts
website-frontend/src/routes/alumni/+page.server.ts
website-frontend/src/routes/alumni/+page.svelte
website-frontend/src/routes/alumni/+page.ts

This pull request includes significant updates to the alumni section of the website, including the addition of new components, models, and API integration. The changes aim to enhance the display and management of alumni data.
Key changes include:
* Added a new `AlumCard` component to display alumni information, including profile and background images, names, titles, descriptions, and accolades.
* Introduced new `Alum` and `Accolade` models to structure the alumni data, replacing the previous `Alumni` model.
* Updated the server-side load function to fetch alumni data and overview from the Directus API.
* Added a client-side load function to pass fetched data to the page.
* Replaced the old `AlumnusCard` component with the new `AlumCard` component and updated the banner to include a …

feat: improve Alumni page

---

website-frontend/src/lib/components/banners/Banner.svelte
website-frontend/src/lib/components/cards/FeaturedEventCard.svelte
website-frontend/src/lib/components/cards/HorizontalCard.svelte
website-frontend/src/routes/events/+page.svelte

- Standardized the `Banner.svelte` component to ensure all banners have a consistent and uniform appearance.
- Fixed a bug in the `FeaturedEventCard` component where multi-day events were incorrectly displayed as whole-day events.
- Updated the `HorizontalCard` component to use the primary color dynamically instead of a hardcoded value.

fix: standardize banner appearance and correct minor card issues

---

website-frontend/src/lib/components/cards/PartnerCard.svelte
website-frontend/src/lib/models/partnerships.ts
website-frontend/src/lib/models/partnerships_overview.ts
website-frontend/src/lib/models/schema.ts
website-frontend/src/routes/partnerships/+page.server.ts
website-frontend/src/routes/partnerships/+page.svelte

This PR loads partnerships data from the backend. This PR also implements come styling fixes on the `PartnerCard` component.

feat(Partnerships): integrate backend

---

website-frontend/src/routes/research/labs/[slug]/+page.svelte

This PR adds reactivity to research lab pages, solving the internal server error upon navigating the research lab pages.

fix: add reactivity to research lab pages

---

website-frontend/src/routes/research/labs/[slug]/+page.svelte
website-frontend/src/routes/research/outputs/+page.svelte

This is a follow up fix PR to #144. It corrects the padding for the lab pages.

fix(layout): correct padding on lab pages

---

website-frontend/src/lib/models/home.ts
website-frontend/src/lib/models/junctions/featured_news.ts
website-frontend/src/lib/models/junctions/recent_events.ts
website-frontend/src/lib/models/junctions/recent_news.ts
website-frontend/src/lib/models/schema.ts
website-frontend/src/routes/+page.server.ts
website-frontend/src/routes/+page.svelte
website-frontend/src/routes/+page.ts

This PR uses a customized carousel for the home page, with display of featured news, recent news, and recent events linked to the configuration in the Directus CMS.

feat: use customized carousel home

---

website-frontend/src/lib/components/sort/Sort.svelte
website-frontend/src/routes/publications/+page.svelte

This PR adds title sort logic to publications.

feat: add title sort logic to publications

---

website-frontend/src/lib/components/cards/PartnerCard.svelte
website-frontend/src/lib/components/cards/PublicationCard.svelte
website-frontend/src/lib/models/partnerships.ts

This PR adds website and email details to partnerships using a modal dialog box, with a similar structure to Publications cards.
This PR also improves spacing to the existing Publications card, for uniformity.

feat: add extra details to partnerships

---

website-frontend/src/lib/components/flexible_content/index.ts

This PR resolves current minor markdown parser issues and removes extraneous attributes from parsed HTML tags.

fix: resolve markdown parser issues

---

website-frontend/src/lib/components/nav/Header.svelte
website-frontend/src/lib/components/nav/NavList.svelte
website-frontend/src/routes/+layout.server.ts
website-frontend/src/routes/+layout.svelte
website-frontend/src/routes/+layout.ts

This PR sets the current navbar to fetch dynamic pages in the Directus CMS.

feat: set navbar to fetch dynamic pages

---

website-frontend/src/lib/components/cards/NewsCard.svelte
website-frontend/src/lib/components/sort/Sort.svelte
website-frontend/src/lib/components/table/CoursesTable.svelte
website-frontend/src/lib/models/junctions/news_related.ts
website-frontend/src/lib/models/news.ts
website-frontend/src/lib/models/news_tags.ts
website-frontend/src/lib/models/schema.ts
website-frontend/src/routes/+page.server.ts
website-frontend/src/routes/news/[slug]/+page.server.ts
website-frontend/src/routes/news/[slug]/+page.svelte

This PR adds display to news tags to necessary news-based components.

feat: add display to news tags

---

website-frontend/src/lib/components/cards/NewsCard.svelte
website-frontend/src/lib/components/table/Calendar.svelte
website-frontend/src/lib/models/event.ts
website-frontend/src/lib/models/news.ts
website-frontend/src/lib/models/publications.ts

This PR provides minor type fixes for tags in model and `+page.svelte` files.

fix: provide type fixes for tags

---

website-frontend/src/lib/components/nav/NavList.svelte
website-frontend/src/routes/people/+page.svelte
website-frontend/src/routes/people/[slug]/+page.svelte
website-frontend/src/routes/research/labs/[slug]/+page.svelte

Hierarchy and some other fixes.

fix: correct hierachy for fellows and TAs positions

---

website-frontend/src/routes/academics/+page.server.ts

This PR adds course sorting by code value in Academics, to align with the one implemented in Academics > [Category] > Courses.

feat: add course sorting preference in academics

---

website-frontend/src/lib/models/about.ts
website-frontend/src/lib/models/about_pages.ts
website-frontend/src/lib/models/academics.ts
website-frontend/src/lib/models/academics_categories.ts
website-frontend/src/lib/models/academics_programs.ts
website-frontend/src/lib/models/events_overview.ts
website-frontend/src/lib/models/miscellaneous_pages.ts
website-frontend/src/lib/models/research.ts
website-frontend/src/lib/models/schema.ts
website-frontend/src/lib/models/students_pages.ts
website-frontend/src/routes/[misc]/+page.svelte
website-frontend/src/routes/about/+page.svelte
website-frontend/src/routes/about/[slug]/+page.svelte
website-frontend/src/routes/academics/+page.svelte
website-frontend/src/routes/academics/[category]/+page.svelte
website-frontend/src/routes/academics/[category]/courses/+page.svelte
website-frontend/src/routes/academics/[category]/programs/[slug]/+page.svelte
website-frontend/src/routes/events/+page.server.ts
website-frontend/src/routes/events/+page.svelte
website-frontend/src/routes/events/+page.ts
website-frontend/src/routes/partnerships/+page.svelte
website-frontend/src/routes/research/+page.server.ts
website-frontend/src/routes/research/+page.svelte
website-frontend/src/routes/research/publications/+page.server.ts
website-frontend/src/routes/research/publications/+page.svelte
website-frontend/src/routes/research/publications/+page.ts
website-frontend/src/routes/students/[slug]/+page.svelte

This PR adds background images for the rest of the web pages with CMS integration.

feat: apply background images
